modLoader="javafml" #mandatory
loaderVersion="[43,45)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL 3"

[[mods]] #mandatory
modId="farmingcompost" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Farming Compost" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Gontrix/farmingcompost/main/update.json" #optional
displayURL="https://gontrix.de/"
logoFile="composting.png" #optional
credits="" #optional
authors="Gontrix"
description='''
Farming Mod with composter
'''

[[dependencies.farmingcompost]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,45)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.farmingcompost]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
